export enum Color {
  APP_BG                  = '$app_bg',
  BLACK                   = '$black',
  DEEP_BLUE               = '$deep_blue',
  DEEP_BLUE_DARK          = '$deep_blue_dark',
  DEEP_BLUE_LIGHT         = '$deep_blue_light',
  FLORAL_GREEN            = '$floral_green',
  FLORAL_GREEN_DARK       = '$floral_green_dark',
  FLORAL_GREEN_LIGHT      = '$floral_green_light',
  INTERSTELLAR_GREY       = '$interstellar_grey',
  INTERSTELLAR_GREY_LIGHT = '$interstellar_grey_light',
  SMOKE_GREY              = '$smoke_grey',
  SMOKE_GREY_LIGHT        = '$smoke_grey_light',
  SUNNY_ORANGE            = '$sunny_orange',
  SUNNY_ORANGE_DARK       = '$sunny_orange_dark',
  SUNNY_ORANGE_LIGHT      = '$sunny_orange_light',
  TEXT_BLUE               = '$text_blue',
  TEXT_BLUE_LIGHT         = '$text_blue_light',
  TEXT_GREY               = '$text_grey',
  TEXT_GREY_LIGHT         = '$text_grey_light',
  VIOLET                  = '$violet',
  WHITE                   = '$white',
}