export enum Color {
  APP_BG                  = '#E0E0E0',
  BLACK                   = '#000000',
  DEEP_BLUE               = '#0465AC',
  DEEP_BLUE_DARK          = '#065188',
  DEEP_BLUE_LIGHT         = '#A2D7E7',
  FLORAL_GREEN            = '#018D31',
  FLORAL_GREEN_DARK       = '#006F26',
  FLORAL_GREEN_LIGHT      = '#ADEDB3',
  INTERSTELLAR_GREY       = '#D2CDEA',
  INTERSTELLAR_GREY_LIGHT = '#46454A',
  SMOKE_GREY              = '#EEEEEE',
  SMOKE_GREY_LIGHT        = '#F8F8F8',
  SUNNY_ORANGE            = '#E76101',
  SUNNY_ORANGE_DARK       = '#C85400',
  SUNNY_ORANGE_LIGHT      = '#FFF6CE',
  TEXT_BLUE               = '#0063BE',
  TEXT_BLUE_LIGHT         = '#0080F6',
  TEXT_GREY               = '#333333',
  TEXT_GREY_LIGHT         = '#909090',
  VIOLET                  = '#3F3664',
  WHITE                   = '#FFFFFF',
}